bot:
    Name: ${TELEGRAM_BOT_NAME}
    Token: ${TELEGRAM_BOT_TOKEN}
spring:
    application:
        name: botShmel
middleService:
    url: ${MIDDLE_URL} #http://localhost:8088
server:
    port: 8080
